version: '3.8'
services:
  ros_core:
    image: ohhorobotics/ros2-jazzy-core:latest
    network_mode: host
    volumes:
      - ./src:/workspace/src
    command: ros2 launch ohho-quadruped_bringup robot.launch.py
  
  digital_twin:
    image: ohhorobotics/isaac-sim-env:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
